### PR TITLE
feat(casbin): add casbin

### PR DESCRIPTION
**Pull request by chenquan**
closes https://github.com/zeromicro/go-zero/issues/1549 
closes https://github.com/casbin/casbin/issues/957 
closes  https://github.com/zeromicro/go-zero/issues/1562

### CODE REVIEW

**Comment by wshxgrong543** [comment]
go get: module github.com/zeromicro/zero-contrib@upgrade found (v1.1.0), but does not contain package github.com/zeromicro/zero-contrib/auth/casbin

**Comment by chenquan** [comment]
close https://github.com/zeromicro/go-zero/issues/1562

**Comment by chenquan** [comment]
closed https://github.com/zeromicro/go-zero/issues/1562

**Comment by chenquan** [comment]
@kevwan @MaxToby PTAL

**Pull request merged**
